name: lint
on: [push, pull_request]
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18.x" ]
    runs-on: ubuntu-latest
    name: "Lint (Go ${{matrix.go}})"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check that go.mod is tidied
        run: |
          cp go.mod /tmp/go.mod.orig
          cp go.sum /tmp/go.sum.orig
          go mod tidy
          diff go.mod /tmp/go.mod.orig
          diff go.sum /tmp/go.sum.orig

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: -v
          skip-pkg-cache: true

      - name: go vet
        run: |
            go vet -tags 'test' ./...

      - name: staticcheck
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck -tags 'test redis' ./...
