name: unit-test
on: [push, pull_request]

jobs:
  unit:
    strategy:
      matrix:
        go: ["1.18.x" ]
    runs-on: ubuntu-latest
    name: Unit tests Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - uses: shogo82148/actions-setup-redis@v1

      - run: go version

      - name: run go test
        run: bash .github/workflows/unit-test.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: /tmp/allcov.out
          env_vars: GO=${{ matrix.go }}
